export default {
	TIPO_SINCRONIZACION: {
		SERVER_VENTA: 1,
		SERVER_COMPRA: 2,
		WEB_VENTA: 3,
		WEB_COMPRA: 4,
		WEB_PRODUCTO: 5,
		SERVER_PRODUCTO: 6,
		WEB_STOCK: 7,
		SERVER_STOCK: 8
	},
	WOO_COMMERCE_ORDER_STATUS_KEYS: {
		PENDING: 'pending',
		PROCESSING: 'processing',
		ON_HOLD: 'on-hold',
		COMPLETED: 'completed',
		CANCELLED: 'cancelled',
		REFUNDED: 'refunded',
		FAILED: 'failed',
	},
	WOO_COMMERCE_ORDER_STATUS: {
		'pending': 1,
		'processing': 2,
		'on-hold': 3,
		'completed': 4,
		'cancelled': 5,
		'refunded': 6,
		'failed': 7,
	},
	TABLENAMES: {
		LAN_COMMERCE_TABLENAME_SINCRONIZACION: Deno.env.get('LAN_COMMERCE_TABLENAME_SINCRONIZACION'),
		LAN_COMMERCE_TABLENAME_PROFORMA_ITEM: Deno.env.get('LAN_COMMERCE_TABLENAME_PROFORMA_ITEM'),
		LAN_COMMERCE_TABLENAME_PROFORMA: Deno.env.get('LAN_COMMERCE_TABLENAME_PROFORMA'),
		LAN_COMMERCE_TABLENAME_TIPOCAMBIO: Deno.env.get('LAN_COMMERCE_TABLENAME_TIPOCAMBIO'),
		LAN_COMMERCE_TABLENAME_PRODUCTOS_PRECIOS: Deno.env.get('LAN_COMMERCE_TABLENAME_PRODUCTOS_PRECIOS'),
		LAN_COMMERCE_TABLENAME_PRODUCTOS: Deno.env.get('LAN_COMMERCE_TABLENAME_PRODUCTOS'),
		LAN_COMMERCE_TABLENAME_PRODUCTOS_STOCKS: Deno.env.get('LAN_COMMERCE_TABLENAME_PRODUCTOS_STOCKS'),
	}
}