import "dotenv";

interface Config {
	TIPO_SINCRONIZACION: { [key: string]: number };
	WOO_COMMERCE_ORDER_STATUS_KEYS: { [key: string]: string };
	WOO_COMMERCE_ORDER_STATUS: { [key: string]: number };
	TABLENAMES: { [key: string]: string | undefined };
	DATABASE_DEFAULT_PORT: number;
	PRODUCT_COLUMNS_TO_SYNC: string[];
}

const config: Config = {
	TIPO_SINCRONIZACION: {
		SERVER_VENTA: 1,
		SERVER_COMPRA: 2,
		WEB_VENTA: 3,
		WEB_COMPRA: 4,
		WEB_PRODUCTO: 5,
		SERVER_PRODUCTO: 6,
		WEB_STOCK: 7,
		SERVER_STOCK: 8,
		SERVER_PRECIO: 9,
		SERVER_CATEGORIA: 10,
	},
	WOO_COMMERCE_ORDER_STATUS_KEYS: {
		PENDING: 'pending',
		PROCESSING: 'processing',
		ON_HOLD: 'on-hold',
		COMPLETED: 'completed',
		CANCELLED: 'cancelled',
		REFUNDED: 'refunded',
		FAILED: 'failed',
	},
	WOO_COMMERCE_ORDER_STATUS: {
		'pending': 1,
		'processing': 2,
		'on-hold': 3,
		'completed': 4,
		'cancelled': 5,
		'refunded': 6,
		'failed': 7,
	},
	TABLENAMES: {
		LAN_COMMERCE_TABLENAME_SINCRONIZACION: Deno.env.get('LAN_COMMERCE_TABLENAME_SINCRONIZACION'),
		LAN_COMMERCE_TABLENAME_PROFORMA_ITEM: Deno.env.get('LAN_COMMERCE_TABLENAME_PROFORMA_ITEM'),
		LAN_COMMERCE_TABLENAME_PROFORMA: Deno.env.get('LAN_COMMERCE_TABLENAME_PROFORMA'),
		LAN_COMMERCE_TABLENAME_TIPOCAMBIO: Deno.env.get('LAN_COMMERCE_TABLENAME_TIPOCAMBIO'),
		LAN_COMMERCE_TABLENAME_PRODUCTOS_PRECIOS: Deno.env.get('LAN_COMMERCE_TABLENAME_PRODUCTOS_PRECIOS'),
		LAN_COMMERCE_TABLENAME_PRODUCTOS: Deno.env.get('LAN_COMMERCE_TABLENAME_PRODUCTOS'),
		LAN_COMMERCE_TABLENAME_PRODUCTOS_STOCKS: Deno.env.get('LAN_COMMERCE_TABLENAME_PRODUCTOS_STOCKS'),
		LAN_COMMERCE_TABLENAME_VENTAS: Deno.env.get('LAN_COMMERCE_TABLENAME_VENTAS'),
		LAN_COMMERCE_TABLENAME_VENTAS_ITEMS: Deno.env.get('LAN_COMMERCE_TABLENAME_VENTAS_ITEMS'),
		LAN_COMMERCE_TABLENAME_COMPRAS: Deno.env.get('LAN_COMMERCE_TABLENAME_COMPRAS'),
		LAN_COMMERCE_TABLENAME_COMPRAS_ITEMS: Deno.env.get('LAN_COMMERCE_TABLENAME_COMPRAS_ITEMS'),
		LAN_COMMERCE_TABLENAME_CATEGORIAS: Deno.env.get('LAN_COMMERCE_TABLENAME_CATEGORIAS'),
	},

	PRODUCT_COLUMNS_TO_SYNC: [
		"id",
		"name",
		"sku",
		"stock_quantity",
		"regular_price",
		"ean"
	],

	DATABASE_DEFAULT_PORT: 1433,
}


export default config;